### ISSUE TITLE
login and registration page

### ISSUE THREAD

**Issue by kyle-liminal** [limlabs/saleor-storefront-starter#111]
Create a new home page for navigating to resources for logged-in users. 

## Dependencies

- #52 

## Mockup

https://www.figma.com/file/6RyYLI5k1zETO9tnsNtATV/Saleor-Template?type=design&node-id=16-602&mode=design&t=Vyfl3dFyqjlBSahe-4

## Register New User

- User enters info to required fields and on submit new account is registered in Saleor "customers"
    - If the user auth token is invalid or missing, redirect the user to /[locale]/account

## SEO

- Title: `Account Home Page`
- Description: `Landing page providing navigation to orders and settings for users with existing accounts.` 
- og:image: none (starter kit user can add this themselves if desired, it's not important for the starter kit itself)

## i18n

Static page content to be stored in [`dictionaries/en-us.json` ](https://github.com/limlabs/saleor-storefront-starter/blob/main/src/dictionaries/en-us.json) (english-only for this story)

- Welcome: `Welcome, <user.firstName>!`
- Navigation
  - Account Settings - `Account Settings`
  - Orders - `Order History`

**Comment by austin-liminal** [comment]
Closing in favor of #126
