### ISSUE TITLE
 [MOCKS] Clean up header on mobile in Figma

### ISSUE THREAD

**Issue by austin-liminal** [limlabs/saleor-storefront-starter#154]
### Description

Currently partially implemented:

- https://www.figma.com/file/6RyYLI5k1zETO9tnsNtATV/Saleor-Template?type=design&node-id=307-552&mode=design&t=gpNODGuf02aVmMyQ-4

Need to finalize:

- Padding uses design system values
- Colors aligning with design system variables

### Acceptance Criteria

- Mobile designs

**Comment by ArturoLiminal** [comment]
https://www.figma.com/file/6RyYLI5k1zETO9tnsNtATV/Saleor-Template?type=design&node-id=307-552&mode=design&t=LORsEWTPKsl2OSeR-4
