### ISSUE TITLE
[MOCKS] Create home page in Figma

### ISSUE THREAD

**Issue by ArturoLiminal** [limlabs/saleor-storefront-starter#157]

**Comment by ArturoLiminal** [comment]
https://www.figma.com/file/6RyYLI5k1zETO9tnsNtATV/Saleor-Template?type=design&node-id=331-1433&mode=design&t=fGEIQu1g8kxW2ZVp-4

**Comment by austin-liminal** [comment]
Mobile is still WIP on this

**Comment by ArturoLiminal** [comment]
Thank you for catching this!
